import{useState,useRef,useEffect}from"react";
const KB={road:"Road complaints → PWD. Avg 3–5 days. Mark High if causing accidents.",water:"Water issues → CMWSSB. No supply = High priority. Avg 2–4 days.",electric:"Electricity → TANGEDCO. Streetlights 2–3 days. Fallen wires = Emergency.",garbage:"Sanitation → GCC. Garbage 1–2 days. Sewage = High, 24 hrs.",status:"Track in 'My Complaints': Pending → In Progress → Resolved.",emergency:"Toggle 'Emergency Mode' to escalate to senior officer within 60 min.",file:"Go to 'Submit Complaint'. Add GPS + photos for 2x faster resolution.",hello:"Hello! I'm EYEWAY AI Assistant. I help with complaints, tracking, and navigation.",help:"I can help: file complaints, track status, departments, emergency, multilingual support."};
function getReply(m){const l=m.toLowerCase();if(l.includes("road")||l.includes("pothole"))return KB.road;if(l.includes("water")||l.includes("pipe"))return KB.water;if(l.includes("electric")||l.includes("light"))return KB.electric;if(l.includes("garbage")||l.includes("sewage"))return KB.garbage;if(l.includes("status")||l.includes("track"))return KB.status;if(l.includes("emergency")||l.includes("urgent"))return KB.emergency;if(l.includes("file")||l.includes("submit"))return KB.file;if(l.includes("hello")||l.includes("hi"))return KB.hello;return KB.help;}
function now(){return new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"});}
export default function AIChatbot(){
  const[open,setOpen]=useState(false);const[input,setInput]=useState("");const[typing,setTyping]=useState(false);
  const[msgs,setMsgs]=useState([{role:"ai",text:"Hello! I'm the EYEWAY AI Assistant 🤖\n\nI help with filing complaints, tracking status, understanding departments, and navigating the portal.\n\nWhat do you need help with?",time:now()}]);
  const ref=useRef(null);
  useEffect(()=>ref.current?.scrollIntoView({behavior:"smooth"}),[msgs,typing]);
  const send=async()=>{if(!input.trim())return;const q=input.trim();setMsgs(p=>[...p,{role:"user",text:q,time:now()}]);setInput("");setTyping(true);await new Promise(r=>setTimeout(r,700+Math.random()*600));setTyping(false);setMsgs(p=>[...p,{role:"ai",text:getReply(q),time:now()}]);};
  return<>
    <button onClick={()=>setOpen(o=>!o)} style={{position:"fixed",bottom:28,right:28,zIndex:500,width:56,height:56,borderRadius:"50%",background:"linear-gradient(135deg,#1a7a6b,#2db49b)",border:"none",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,boxShadow:"0 6px 24px rgba(45,180,155,.55)",transition:"all .3s",animation:open?"none":"pulse-glow 2.5s ease infinite"}} onMouseEnter={e=>e.currentTarget.style.transform="scale(1.1)"} onMouseLeave={e=>e.currentTarget.style.transform="scale(1)"}>{open?"✕":"🤖"}</button>
    {open&&<div style={{position:"fixed",bottom:96,right:28,zIndex:499,width:340,maxHeight:520,background:"#131927",border:"1px solid rgba(45,180,155,.25)",borderRadius:18,boxShadow:"0 24px 80px rgba(0,0,0,.65)",display:"flex",flexDirection:"column",overflow:"hidden",animation:"fadeUp .3s ease"}}>
      <div style={{padding:"13px 18px",background:"linear-gradient(135deg,#1a7a6b,#2db49b)",display:"flex",alignItems:"center",gap:12}}><div style={{width:36,height:36,borderRadius:"50%",background:"rgba(255,255,255,.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}}>🤖</div><div><div style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:700,fontSize:14,color:"#fff"}}>EYEWAY AI</div><div style={{fontSize:11,color:"rgba(255,255,255,.75)",display:"flex",alignItems:"center",gap:5}}><span style={{width:6,height:6,borderRadius:"50%",background:"#4ade80",display:"inline-block"}}/>Online</div></div></div>
      <div style={{flex:1,overflowY:"auto",padding:14,display:"flex",flexDirection:"column",gap:10,minHeight:180,maxHeight:280}}>
        {msgs.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start",gap:8}}>
          {m.role==="ai"&&<div style={{width:26,height:26,borderRadius:"50%",background:"linear-gradient(135deg,#1a7a6b,#2db49b)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,flexShrink:0,marginTop:2}}>🤖</div>}
          <div style={{maxWidth:"80%"}}><div style={{padding:"10px 13px",borderRadius:m.role==="user"?"14px 14px 4px 14px":"14px 14px 14px 4px",background:m.role==="user"?"linear-gradient(135deg,#1a7a6b,#2db49b)":"rgba(255,255,255,.07)",border:m.role==="ai"?"1px solid rgba(255,255,255,.1)":"none",fontSize:13,color:"#fff",lineHeight:1.6,whiteSpace:"pre-wrap"}}>{m.text}</div><div style={{fontSize:10,color:"rgba(255,255,255,.3)",marginTop:3,textAlign:m.role==="user"?"right":"left"}}>{m.time}</div></div>
        </div>)}
        {typing&&<div style={{display:"flex",gap:8}}><div style={{width:26,height:26,borderRadius:"50%",background:"linear-gradient(135deg,#1a7a6b,#2db49b)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12}}>🤖</div><div style={{padding:"10px 14px",background:"rgba(255,255,255,.07)",borderRadius:"14px 14px 14px 4px",border:"1px solid rgba(255,255,255,.1)",display:"flex",gap:4,alignItems:"center"}}>{[0,1,2].map(i=><span key={i} style={{width:6,height:6,borderRadius:"50%",background:"#2db49b",display:"inline-block",animation:`wave .9s ease ${i*.2}s infinite`}}/>)}</div></div>}
        <div ref={ref}/>
      </div>
      <div style={{padding:"0 12px 8px",display:"flex",gap:6,flexWrap:"wrap"}}>{["Track complaint","Road issue","Water problem","Emergency"].map(q=><button key={q} onClick={()=>setInput(q)} style={{padding:"4px 10px",borderRadius:999,background:"rgba(45,180,155,.1)",border:"1px solid rgba(45,180,155,.25)",color:"#2db49b",fontSize:11,fontWeight:600,cursor:"pointer"}}>{q}</button>)}</div>
      <div style={{padding:"10px 12px",borderTop:"1px solid rgba(255,255,255,.07)",display:"flex",gap:8}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask about complaints..." style={{flex:1,padding:"9px 12px",background:"rgba(255,255,255,.06)",border:"1px solid rgba(255,255,255,.1)",borderRadius:9,color:"#fff",fontSize:13,fontFamily:"'Inter',sans-serif",outline:"none"}}/><button onClick={send} style={{padding:"9px 14px",background:"linear-gradient(135deg,#1a7a6b,#2db49b)",border:"none",color:"#fff",borderRadius:9,cursor:"pointer",fontSize:16}}>➤</button></div>
    </div>}
    <style>{`@keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}} @keyframes wave{0%,100%{transform:scaleY(.3)}50%{transform:scaleY(1)}} @keyframes pulse-glow{0%,100%{box-shadow:0 6px 24px rgba(45,180,155,.55)}50%{box-shadow:0 6px 40px rgba(45,180,155,.8)}}`}</style>
  </>;
}
