import{BarChart,Bar,LineChart,Line,PieChart,Pie,Cell,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer}from"recharts";
const COLORS=["#2db49b","#3b9eff","#f59e0b","#a78bfa","#22c55e","#f47920","#ef4444","#06b6d4"];
const TT={contentStyle:{background:"#1a2236",border:"1px solid rgba(45,180,155,.2)",borderRadius:10,fontFamily:"'Inter',sans-serif",fontSize:13},labelStyle:{color:"#fff",fontWeight:600},itemStyle:{color:"rgba(255,255,255,.7)"}};
export function MonthlyChart({data}){
  const d=data||[{m:"Jan",c:62,r:45},{m:"Feb",c:78,r:60},{m:"Mar",c:55,r:50},{m:"Apr",c:90,r:72},{m:"May",c:74,r:68},{m:"Jun",c:95,r:80},{m:"Jul",c:88,r:77},{m:"Aug",c:102,r:89},{m:"Sep",c:76,r:70},{m:"Oct",c:115,r:98},{m:"Nov",c:91,r:85},{m:"Dec",c:130,r:112}];
  return<ResponsiveContainer width="100%" height={210}><BarChart data={d} margin={{top:5,right:10,left:-20,bottom:5}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.05)"/><XAxis dataKey="m" tick={{fill:"rgba(255,255,255,.4)",fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"rgba(255,255,255,.4)",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip {...TT}/><Legend wrapperStyle={{fontSize:12,color:"rgba(255,255,255,.45)"}}/><Bar dataKey="c" name="Filed" fill="#3b9eff" radius={[4,4,0,0]} opacity={.8}/><Bar dataKey="r" name="Resolved" fill="#2db49b" radius={[4,4,0,0]} opacity={.85}/></BarChart></ResponsiveContainer>;
}
export function CategoryChart({data}){
  const d=data?Object.entries(data).map(([n,v])=>({name:n,value:v})):[{name:"Roads",value:34},{name:"Water",value:22},{name:"Electric",value:18},{name:"Sanitation",value:14},{name:"Other",value:12}];
  return<ResponsiveContainer width="100%" height={210}><PieChart><Pie data={d} cx="50%" cy="50%" innerRadius={50} outerRadius={80} paddingAngle={3} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`} labelLine={{stroke:"rgba(255,255,255,.2)",strokeWidth:1}}>{d.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]} opacity={.87}/>)}</Pie><Tooltip {...TT}/></PieChart></ResponsiveContainer>;
}
export function TrendChart({data}){
  const d=data||[{day:"Mon",rate:72},{day:"Tue",rate:68},{day:"Wed",rate:80},{day:"Thu",rate:75},{day:"Fri",rate:85},{day:"Sat",rate:78},{day:"Sun",rate:90}];
  return<ResponsiveContainer width="100%" height={170}><AreaChart data={d} margin={{top:5,right:10,left:-20,bottom:5}}><defs><linearGradient id="tG" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2db49b" stopOpacity={.35}/><stop offset="95%" stopColor="#2db49b" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.05)"/><XAxis dataKey="day" tick={{fill:"rgba(255,255,255,.4)",fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"rgba(255,255,255,.4)",fontSize:11}} axisLine={false} tickLine={false} domain={[50,100]}/><Tooltip {...TT} formatter={v=>[`${v}%`,"Rate"]}/><Area type="monotone" dataKey="rate" stroke="#2db49b" strokeWidth={2.5} fill="url(#tG)"/></AreaChart></ResponsiveContainer>;
}
export function DeptChart(){
  const d=[{dept:"Roads",resolved:89,pending:12},{dept:"Water",resolved:76,pending:8},{dept:"Electric",resolved:94,pending:4},{dept:"Sanitation",resolved:61,pending:20},{dept:"Health",resolved:82,pending:9}];
  return<ResponsiveContainer width="100%" height={190}><BarChart data={d} layout="vertical" margin={{top:5,right:10,left:20,bottom:5}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.05)" horizontal={false}/><XAxis type="number" tick={{fill:"rgba(255,255,255,.4)",fontSize:11}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="dept" tick={{fill:"rgba(255,255,255,.55)",fontSize:12}} axisLine={false} tickLine={false} width={60}/><Tooltip {...TT}/><Bar dataKey="resolved" name="Resolved" fill="#2db49b" radius={[0,4,4,0]} stackId="a" opacity={.85}/><Bar dataKey="pending" name="Pending" fill="#f59e0b" radius={[0,4,4,0]} stackId="a" opacity={.75}/></BarChart></ResponsiveContainer>;
}
export function ActivityChart(){
  const d=Array.from({length:30},(_,i)=>({day:`${i+1}`,users:Math.floor(120+Math.random()*200),complaints:Math.floor(20+Math.random()*80)}));
  return<ResponsiveContainer width="100%" height={190}><LineChart data={d} margin={{top:5,right:10,left:-20,bottom:5}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.05)"/><XAxis dataKey="day" tick={{fill:"rgba(255,255,255,.3)",fontSize:10}} axisLine={false} tickLine={false} tickFormatter={(v,i)=>i%5===0?v:""}/><YAxis tick={{fill:"rgba(255,255,255,.4)",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip {...TT}/><Legend wrapperStyle={{fontSize:12,color:"rgba(255,255,255,.45)"}}/><Line type="monotone" dataKey="users" name="Active Users" stroke="#3b9eff" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="complaints" name="Complaints" stroke="#f59e0b" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer>;
}
