import{useEffect,useRef,useState}from"react";
const DATA=[{id:"C001",lat:13.0827,lng:80.2707,title:"Large Pothole - MG Road",status:"pending",priority:"high",category:"Roads",citizen:"Priya S."},{id:"C002",lat:13.0900,lng:80.2500,title:"Water Pipe Burst - Anna Nagar",status:"in_progress",priority:"high",category:"Water",citizen:"Rahul M."},{id:"C003",lat:13.0600,lng:80.2800,title:"Streetlight Broken - T Nagar",status:"resolved",priority:"medium",category:"Electric",citizen:"Anita K."},{id:"C004",lat:13.1000,lng:80.2100,title:"Garbage Overflow - Porur",status:"pending",priority:"medium",category:"Sanitation",citizen:"Mohan R."},{id:"C005",lat:13.0450,lng:80.2100,title:"Road Damage - Guindy",status:"in_progress",priority:"high",category:"Roads",citizen:"Sneha J."},{id:"C006",lat:13.1200,lng:80.2400,title:"No Water - Ambattur",status:"pending",priority:"high",category:"Water",citizen:"Kiran V."},{id:"C007",lat:13.0750,lng:80.2600,title:"Park Bench Broken",status:"resolved",priority:"low",category:"Parks",citizen:"Ravi P."},{id:"C008",lat:13.0550,lng:80.2650,title:"Sewage Overflow - Adyar",status:"pending",priority:"high",category:"Sanitation",citizen:"Meena R."},{id:"C009",lat:13.0700,lng:80.2300,title:"Traffic Signal Faulty",status:"resolved",priority:"medium",category:"Roads",citizen:"Suresh K."},{id:"C010",lat:13.0350,lng:80.2550,title:"Flood Water - Chromepet",status:"in_progress",priority:"high",category:"Sanitation",citizen:"Lalitha M."}];
const SC={pending:{color:"#ef4444",label:"Pending"},in_progress:{color:"#f59e0b",label:"In Progress"},resolved:{color:"#22c55e",label:"Resolved"}};
const PR={high:14,medium:10,low:7};
export default function ComplaintMap({height=440}){
  const mapRef=useRef(null);const instRef=useRef(null);const[sel,setSel]=useState(null);const[filter,setFilter]=useState("all");
  useEffect(()=>{
    if(instRef.current)return;
    if(!document.getElementById("lflt-css")){const l=document.createElement("link");l.id="lflt-css";l.rel="stylesheet";l.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(l);}
    const init=()=>{
      if(!mapRef.current||!window.L||instRef.current)return;
      const map=window.L.map(mapRef.current,{center:[13.0827,80.2707],zoom:12,zoomControl:true,attributionControl:false});
      window.L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{subdomains:"abcd",maxZoom:19}).addTo(map);
      DATA.forEach(c=>{
        const cfg=SC[c.status]||SC.pending;const r=PR[c.priority]||10;
        const m=window.L.circleMarker([c.lat,c.lng],{radius:r,fillColor:cfg.color,color:cfg.color,weight:2,opacity:1,fillOpacity:.75}).addTo(map);
        if(c.priority==="high")window.L.circleMarker([c.lat,c.lng],{radius:r+5,fillColor:"transparent",color:cfg.color,weight:1,opacity:.3,fillOpacity:0}).addTo(map);
        m.bindPopup(`<div style="font-family:'Inter',sans-serif;min-width:190px;padding:4px"><div style="display:flex;justify-content:space-between;margin-bottom:8px"><span style="font-size:11px;color:#94a3b8;font-weight:600">#${c.id}</span><span style="font-size:11px;font-weight:700;padding:2px 9px;border-radius:999px;background:${cfg.color}22;color:${cfg.color}">${cfg.label}</span></div><div style="font-size:14px;font-weight:700;color:#fff;margin-bottom:6px">${c.title}</div><div style="font-size:12px;color:#94a3b8">📂 ${c.category} · 👤 ${c.citizen}</div><div style="margin-top:9px;font-size:11px;font-weight:700;color:${c.priority==="high"?"#ef4444":c.priority==="medium"?"#f59e0b":"#22c55e"}">${c.priority.toUpperCase()} PRIORITY</div></div>`,{className:"eyeway-popup"});
        m.on("click",()=>setSel(c));
      });
      instRef.current=map;
    };
    if(window.L)init();else{const s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=init;document.head.appendChild(s);}
    return()=>{if(instRef.current){instRef.current.remove();instRef.current=null;}};
  },[]);
  const stats={all:DATA.length,pending:DATA.filter(c=>c.status==="pending").length,in_progress:DATA.filter(c=>c.status==="in_progress").length,resolved:DATA.filter(c=>c.status==="resolved").length};
  return<div>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}>{[["all","All",stats.all,"#94a3b8"],["pending","Pending",stats.pending,"#ef4444"],["in_progress","In Progress",stats.in_progress,"#f59e0b"],["resolved","Resolved",stats.resolved,"#22c55e"]].map(([v,l,n,c])=><button key={v} onClick={()=>setFilter(v)} style={{padding:"5px 14px",borderRadius:999,cursor:"pointer",fontFamily:"'Inter',sans-serif",fontSize:12,fontWeight:600,background:filter===v?`${c}22`:"rgba(255,255,255,.04)",border:`1px solid ${filter===v?`${c}55`:"rgba(255,255,255,.1)"}`,color:filter===v?c:"rgba(255,255,255,.5)",display:"flex",alignItems:"center",gap:6}}><span style={{width:7,height:7,borderRadius:"50%",background:c,display:"inline-block"}}/>{l} ({n})</button>)}</div>
    <div style={{position:"relative",borderRadius:16,overflow:"hidden",border:"1px solid rgba(45,180,155,.2)",boxShadow:"0 8px 32px rgba(0,0,0,.4)"}}>
      <div ref={mapRef} style={{height,width:"100%",background:"#0e1420"}}/>
      <div style={{position:"absolute",bottom:12,left:12,zIndex:1000,background:"rgba(14,20,32,.92)",border:"1px solid rgba(45,180,155,.2)",borderRadius:10,padding:"11px 15px",backdropFilter:"blur(12px)"}}><div style={{fontSize:10,fontWeight:800,color:"rgba(255,255,255,.4)",letterSpacing:"0.08em",marginBottom:8}}>STATUS</div>{Object.entries(SC).map(([k,v])=><div key={k} style={{display:"flex",alignItems:"center",gap:7,marginBottom:5}}><div style={{width:8,height:8,borderRadius:"50%",background:v.color}}/><span style={{fontSize:12,color:"rgba(255,255,255,.65)"}}>{v.label}</span></div>)}<div style={{marginTop:8,paddingTop:8,borderTop:"1px solid rgba(255,255,255,.07)",fontSize:11,color:"rgba(255,255,255,.3)"}}>Size = priority</div></div>
      <div style={{position:"absolute",top:12,right:12,zIndex:1000,background:"rgba(14,20,32,.92)",border:"1px solid rgba(45,180,155,.25)",borderRadius:10,padding:"10px 15px",backdropFilter:"blur(12px)"}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:4}}><div style={{width:7,height:7,borderRadius:"50%",background:"#22c55e",animation:"ping 1.5s ease infinite"}}/><span style={{fontSize:10,fontWeight:700,color:"#22c55e",letterSpacing:"0.06em"}}>LIVE</span></div><div style={{fontSize:24,fontWeight:900,color:"#2db49b",fontFamily:"'Space Grotesk',sans-serif"}}>{DATA.length}</div><div style={{fontSize:11,color:"rgba(255,255,255,.35)"}}>Complaints</div></div>
    </div>
    {sel&&<div style={{marginTop:12,background:"rgba(26,34,54,.9)",border:`1px solid ${SC[sel.status].color}44`,borderRadius:12,padding:"13px 18px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10,animation:"fadeIn .2s ease"}}><div><div style={{display:"flex",gap:8,marginBottom:4,alignItems:"center"}}><span style={{fontSize:11,color:"#2db49b",fontWeight:600}}>#{sel.id}</span><span style={{fontSize:11,padding:"2px 8px",borderRadius:999,background:`${SC[sel.status].color}22`,color:SC[sel.status].color,fontWeight:700}}>{SC[sel.status].label}</span></div><div style={{fontSize:14,fontWeight:600,color:"#fff",marginBottom:2}}>{sel.title}</div><div style={{fontSize:12,color:"rgba(255,255,255,.4)"}}>📂 {sel.category} · 👤 {sel.citizen}</div></div><button onClick={()=>setSel(null)} style={{background:"none",border:"none",color:"rgba(255,255,255,.3)",cursor:"pointer",fontSize:18}}>✕</button></div>}
    <style>{`@keyframes ping{0%{transform:scale(1);opacity:1}100%{transform:scale(2.2);opacity:0}} @keyframes fadeIn{from{opacity:0}to{opacity:1}}`}</style>
  </div>;
}
